modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="epic_engine"
version="1.0.0"
displayName="Epic Engine"
displayURL="None"
credits="None"
authors="CJianqgiu"
logoFile="assets/epic_engine/textures/logo.png"
[[dependencies.epic_engine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"



